name: Auto-Renaming
on:
  workflow_call:
    inputs:
      username:
        description: 'Your username'
        default: ${{ github.repository_owner }}
        required: false
        type: string
      modname:
        description: 'Your mod name'
        default: ${{ github.event.repository.name }}
        required: false
        type: string

jobs:
  rename:
    
